### ISSUE TITLE
پرش از صفحه

### ISSUE THREAD

**Issue by zarrinnegar** [Mds92/Mds92.github.io#2]
با سلام
من از این تقویم در پروژه استفاده کردم ولی نمیدانم چرا با هر بار کلیک روی صفحه تقویم بحتی برای جابجایی ماهها و یا سالها بعد از کلیک صفحه مخفی میشود
لطفا در صورت امکان به ایمیل zarrinnegar@gmail.com ارسال نمایید

**Comment by Mds92** [comment]
سلام
وقت بخیر
این کتابخانه خیلی وقت هست دیکه بروزنمی شود
از کتابخانه های دیگر استفاده نمائید

**Comment by zarrinnegar** [comment]
سلام
ممنون که پاسخ دادید
هر کتابخانه ای را انتخاب میکنم با jquery قالبم کلنفلیکت میکنه و کلی خطا
میده این تنها کتابخانه ای بود که بوت استرپی بود و مشکلی باهاش نداشتم
احتمالا پرشش هم بخاطر ناسازگاری با query هایی هست که لود میشن

اگر کتابخانه ای سراغ دارید معرفی کنید ممنون میشم

باز هم متشکرم
